# Generated by Django 5.1 on 2024-11-04 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_remove_paciente_alergias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='documentos_pacientes/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Documento do Paciente',
                'verbose_name_plural': 'Documentos dos Pacientes',
                'ordering': ['-data_upload'],
            },
        ),
    ]
