# Generated by Django 5.1 on 2024-11-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_documentopaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('NEGADO', 'Negado')], default='PENDENTE', max_length=10),
        ),
    ]
