# Generated by Django 5.1 on 2024-09-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('numero_residencia', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
    ]
