# Generated by Django 5.1 on 2024-11-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_alter_endereco_bairro_alter_endereco_cep_and_more'),
        ('usuario', '0003_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco', verbose_name='endereço'),
        ),
    ]
