# Generated by Django 5.1 on 2024-08-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField(blank=True, null=True)),
                ('medico', models.CharField(max_length=255)),
                ('laudo_final', models.CharField(max_length=255)),
                ('prescricoes', models.TextField()),
                ('exames_solicitados', models.CharField(max_length=255)),
            ],
        ),
    ]
