# Generated by Django 5.1 on 2024-08-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
